# Generated by Django 4.2.5 on 2023-10-06 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('rating', models.IntegerField(default=0)),
                ('job', models.BooleanField()),
                ('balance', models.FloatField(default=0)),
            ],
        ),
    ]
