# Generated by Django 4.2.5 on 2023-10-06 01:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.FloatField()),
                ('description', models.TextField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='client_name', to='user_profile.users')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orders.status')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='worker_name', to='user_profile.users')),
            ],
        ),
    ]
